#!/usr/bin/env node
// Generates every copy of the design tokens from 2-design-system/tokens.json:
//   - 2-design-system/tokens.css
//   - the token block in 1-learning-hub/source/part1.html (between the tokens:start and tokens:end comment markers)
//   - the token + component prefix of 2-design-system/components-gallery.html
// Run `node tools/build-tokens.js` to write, `node tools/build-tokens.js --check` to fail on drift.
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');
const check = process.argv.includes('--check');

const tj = JSON.parse(read('2-design-system/tokens.json'));
const decl = (name, v) => `--${name}:${v}`;
const colors = th => tj.color.tokens.map(t => decl(t.name, t.value[th]));
const shadow = th => tj.shadow.tokens.map(t => decl(t.name, t.value[th]));
const scale = [
  ...tj.spacing.tokens, ...tj.radius.tokens, ...tj.motion.tokens, ...tj.zindex.tokens,
].map(t => decl(t.name, t.value));
const fonts = [decl('font-sans', tj.type.families.sans), decl('font-mono', tj.type.families.mono)];
const rows = (list, n = 6) => list.reduce((s, d, i) => s + d + ';' + ((i + 1) % n === 0 ? '\n' : ''), '');
const block = (sel, list) => `${sel}{${list.length > 6 ? '\n' : ''}${rows(list)}}`;

const light = [...colors('light'), ...shadow('light')];
const dark = [...colors('dark'), ...shadow('dark')];
const constant = [...scale, ...fonts];

const tokensCss =
  `/* Generated by tools/build-tokens.js from tokens.json. Do not edit by hand. */\n` +
  block(':root,[data-theme=light]', light) + '\n' +
  block('[data-theme=dark]', ['color-scheme:dark', ...dark]) + '\n' +
  block(':root', constant) + '\n';

const hubBlock =
  `/*tokens:start - generated by tools/build-tokens.js from 2-design-system/tokens.json, do not edit by hand*/\n` +
  block(':root', [...light, ...constant]) + '\n' +
  `@media (prefers-color-scheme:dark){${block(':root:not([data-theme="light"])', ['color-scheme:dark', ...dark])}}\n` +
  block(':root[data-theme="dark"]', ['color-scheme:dark', ...dark]) + '\n' +
  `/*tokens:end*/`;

const outputs = [];
outputs.push(['2-design-system/tokens.css', tokensCss]);

let part = read('1-learning-hub/source/part1.html');
const markers = /\/\*tokens:start[\s\S]*?\/\*tokens:end\*\//;
if (!markers.test(part)) throw new Error('part1.html is missing the /*tokens:start*/ ... /*tokens:end*/ markers');
outputs.push(['1-learning-hub/source/part1.html', part.replace(markers, () => hubBlock)]);

const bundle = read('2-design-system/components/bundle.css');
let gal = read('2-design-system/components-gallery.html');
const galRe = /^<style>[\s\S]*?(?=\.g-top\{)/m;
if (!galRe.test(gal)) throw new Error('components-gallery.html: could not find the style prefix');
outputs.push(['2-design-system/components-gallery.html', gal.replace(galRe, () => '<style>' + tokensCss + bundle + '\n')]);

let drift = 0;
for (const [file, content] of outputs) {
  const cur = read(file);
  if (cur === content) { console.log('up to date  ' + file); continue; }
  drift++;
  if (check) console.log('DRIFT       ' + file);
  else { fs.writeFileSync(path.join(root, file), content); console.log('wrote       ' + file); }
}
if (check && drift) { console.error('Tokens are out of sync. Run: node tools/build-tokens.js'); process.exit(1); }
